move:
  target:
    device:
      integration: icsee_ptz
  fields:
    cmd:
      example: "DirectionUp"
      default: "DirectionUp"
      required: true
      selector:
        select:
          options:
            - Stop
            - DirectionUp
            - DirectionDown
            - DirectionLeft
            - DirectionRight
            - DirectionLeftUp
            - DirectionLeftDown
            - DirectionRightUp
            - DirectionRightDown
            - ZoomTile
            - ZoomWide
            - FocusNear
            - FocusFar
            - IrisSmall
            - IrisLarge
            - SetPreset
            - GotoPreset
            - ClearPreset
            - StartTour
            - StopTour
    step:
      default: 2
      selector:
        number:
          min: 0
          max: 10
    preset:
      default: 0
      selector:
        number:
          mode: box
          min: 0
          max: 100
synchronize_clock:
  target:
    device:
      integration: icsee_ptz
force_frame:
  target:
    device:
      integration: icsee_ptz
